update gallery_picture set category_id = 2 where name = 'pic0814029';
update gallery_picture set category_id = 6 where name = 'pic0814044';
update gallery_picture set category_id = 2 where name = 'pic0814064';
update gallery_picture set category_id = 6 where name = 'pic0814049';
update gallery_picture set category_id = 5 where name = 'pic0814073';
update gallery_picture set category_id = 4 where name = 'pic0814077';
update gallery_picture set category_id = 4 where name = 'pic0814088';
update gallery_picture set category_id = 4 where name = 'pic0814093';
update gallery_picture set category_id = 5 where name = 'pic0814095';
update gallery_picture set category_id = 2 where name = 'pic0814097';
update gallery_picture set category_id = 2 where name = 'pic0814100';
update gallery_picture set category_id = 2 where name = 'pic0814101';
update gallery_picture set category_id = 2 where name = 'pic0814106';
update gallery_picture set category_id = 6 where name = 'pic0814145';
update gallery_picture set category_id = 6, description = 'Schaukasten im Husqvarna Fabrikmuseum.' where name = 'pic0814148';
update gallery_picture set category_id = 6, description = 'Nähmaschine Husqvarna Compact 3600.' where name = 'pic0814149';
update gallery_picture set category_id = 2 where name = 'pic0814154';
update gallery_picture set category_id = 2 where name = 'pic0814162';
update gallery_picture set category_id = 5 where name = 'pic0814192';
update gallery_picture set category_id = 4, description = 'Sommerhaus am Örken See bei Lilla Näs. Aus dem Kanu aufgenommen und deshalb minimal unscharf.' where name = 'pic0814195';

delete from gallery_picture where category_id = 1;
