<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ include file="/jsp/include/doctype.jspf"%>
<%@ include file="/jsp/include/environment.jspf"%>
<%@ include file="/jsp/include/htmlhead_start.jspf"%>
<%@ include file="/jsp/include/title.jspf"%>
<%@ include file="/jsp/include/head.jspf"%>
<link rel="stylesheet" type="text/css" href="/css/travels.css${contentVersionParam}" />
<link rel="stylesheet" type="text/css" href="/lib/colorbox/colorbox.css" />
<script type="text/javascript" src="/lib/jquery.colorbox-min.js"></script>
<script type="text/javascript" src="/lib/jquery.placeholder.min.js"></script>
<script type="text/javascript" src="/js/comment.js" ></script>
<%@ include file="/jsp/include/htmlhead_end.jspf"%>
<%@ include file="/jsp/include/htmlbody_start.jspf"%>
<%@ include file="/jsp/include/header.jspf"%>
<%@ include file="/jsp/include/nav_main.jspf"%>
<section id="content" class="travel story">
	<article id="contentWrap">
		<header id="contentHeader">
			<h1>Einmal um die Ostsee</h1>
			<p><strong>Ein Reisebericht über eine 3-monatige Campingtour Skandinavien und Baltikum</strong></p>
			<p>20.09.2014</p>
		</header>
		<section id="contentMain">
			<p>Wir waren schon mehrmals in Dänemark und <a class="arrow" href="<c:url value="${displayCategoryURLs['sweden']}" />">Schweden</a>. Auch den <a class="arrow" href="<c:url value="${displayCategoryURLs['poland']}" />">Norden Polens</a> hatten wir 2011 mit dem Campingbus erkundet. Es schwirrte aber schon lange Zeit die Vorstellung in meinen Kopf, einmal um die Ostsee zu fahren. Damit würden wir auch mal Finnland sehen. Und einen Teil der baltischen Länder. Über Estland und der Kurischen Nehrung hatten wir schon einige Reportagen im Fernsehen gesehen und für interessant befunden.</p>
			<h2>Vorbereitung</h2>
			<p>So sollte es dieses Jahr nun also endlich klappen. Die Vorbereitungen fingen bereits im Winter 2014 an. Dazu hatten wir die ungefähre Route geplant und für einen mehrwöchigen Aufenthalt auf Saaremaa in Estland ein kleines Ferienhaus gebucht. Für die Reise hatten wir insgesamt 3 Monate veranschlagt. Wegen den großen Entfernungen Richtung Norden wollten wir nicht die ganze Ostseeküste bereisen. Stattdessen haben wir im Norden zwischen Schweden und Finnland abgekürzt und einen Sprung über die sehr schöne Insel Åland gemacht. St. Petersburg und die russische Exklave Kaliningrad wollen wir wegen dem Ukraine-Konflikt auslassen.</p>
			<p>Im Frühjahr gingen die Vorbereitungen weiter: FSME- und Tetanusimpfung auffrischen. Den VW-Bus klar machen. In welchen Ländern wird mit welcher Währung bezahlt? Und wie kann man zumindest in Estland günstig im Internet surfen? Wo kann man auf der Gauja paddeln? Meistens haben wir direkt mit der EC-Karte bezahlt. Lediglich für Estland (Saaremaa) und Litauen (Kurische Nehrung) hatten wir uns Bargeld am Automaten gezogen. Da wir in Estland 6 Wochen bleiben würden, lohnte sich der Kauf einer Prepaid-Karte im <a href="https://www.emt.ee/en/kontakt/esindused" rel="nofollow">Elion-Shop<i class="fa fa-external-link"></i></a> in Tallinn. Ansonsten ist Internet in Skandinavien und im Baltikum weit verbreitet. Es gibt fast überall Netz und eigentlich jedes Lokal, jedes Café oder Restaurant hat WiFi. Viele Campingplätze auch. Und zwar kostenlos.</p>
			<h2>Abfahrt</h2>
			<a class="storyImage right" href="<c:out value="${imageServerUrl}${pictures['p1406002'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406002'].title}"><img alt="${pictures['p1406002'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406002'].image.imageUris['galleryStory']}" />" /></a>
			<p>Am Samstag, den 7. Juni geht es endlich los. Der VW-Bus ist samt Dachbox und Fahrradträger gut bepackt. Für 2 Personen und 3 Monate müssen auch einige Lebensmittel mit. Weil natürlich nicht klar ist, welches Wetter zu erwarten sein wird, eben auch Kleidung für Warm, Kalt, Heiß und Nass. Uneinig waren wir uns über die Notwendigkeit eines Vorzeltes. In letzter Minute wurde dann aber doch noch das <a href="http://www.fritz-berger.de/campingartikel/bvz-touring-easy.htm" rel="nofollow">Berger Touring easy<i class="fa fa-external-link"></i></a> gekauft und es hat zumindest in den kühlen und von Mücken erfüllten Abendstunden einen guten Job gemacht. Als eine gewisse Sicherheit darüber einkehrt, nichts vergessen zu haben, drehe ich den Zündschlüssel und die Fahrt über mehrere Tausend Kilometer beginnt in Hamburg Nahe der A7 Richtung Dänemark. Statt der üblichen Route Puttgarden/ Rödby wählen wir den Umweg über die Öresund-Brücke und Fynen. Das spart etwa 40 Euro und wir verbringen die ersten sonnigen Tage an der landschaftlich schönen Nordspitze Hindsholm auf Fynen. Zur Halbinsel mit dem kleinen Naturschutzgebiet <a href="http://www.hindsholm.com/Vandretur_Fyns_Hoved.htm" rel="nofollow">Fyns Hoved<i class="fa fa-external-link"></i></a> gehört auch eine Steilküste, an der wir bei einem Becher Rotwein die Sonne über dem Samsö Bält untergehen sehen. Ein fulminanter Start in den Urlaub.</p>
			<h2>Schweden</h2>
			<p>Am frühen Morgen geht es dann zeitig zur Fähre Helsingör/Helsingborg. Das Ticket braucht nicht gebucht werden und die Überfahrt dauert nur eine halbe Stunde. Da wir Südschweden schon kennen, nehmen wir auch hier die Autobahn. Die E4 Richtung Stockholm ist gut befahrbar und hat gemessen an deutschen Verhältnissen wenig Verkehr. Wir genießen wie immer in Schweden das allgemeine Tempolimit und die damit verbundene Ruhe und Rücksichtnahme. Am See Bolmen bei Ljungby machen wir ein kleines Picknick. Obwohl wir als Touristen ein wenig auffallen, entscheiden wir uns spontan, am See zu übernachten.</p>
			<a class="storyImage left" href="<c:out value="${imageServerUrl}${pictures['p1406021'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406021'].title}"><img alt="${pictures['p1406021'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406021'].image.imageUris['galleryStory']}" />" /></a>
			<p>Im weiteren Verlauf wählen wir den <a href="http://www.flatenbadetscamping.se/" rel="nofollow">Campingplatz nahe Hillerstorp<i class="fa fa-external-link"></i></a> am See Flaten. Dieser Platz ist sehr schön gelegen und obwohl es schon Juni ist, können wir uns eine Fläche ohne direkte Nachbarn aussuchen. Der Grund für die Platzwahl ist der <a href="http://www.storemosse.se/" rel="nofollow">Nationalpark Store Mosse<i class="fa fa-external-link"></i></a>, den wir mit dem Fahrrad besuchen. Store Mosse ist das größte Moorgebiet Südschwedens. Durch das Moor führt ein teilweise mit Stegen ausgebauter 40 Kilometer langer Wanderweg. Wir sehen einen Teil davon, weil die Mittagshitze das Wandern anstrengend macht. Schaut man in die Ferne, wirkt die Landschaft herrlich öde. Schaut man auf das Moor, entdeckt man eine vielfältige Pflanzenwelt. Sonnentau ist überall zusehen. Wir kehren nach 10 Kilometer um und fahren mit den Fahrrädern zurück zum Campingplatz, wo eine Abkühlung im See wartet. Jedenfalls, wenn man die 200m durch das überraschend flache Ufer überwindet.</p>
			<p>Klar ist, dass wir an diesem herrlichen Platz am blauen See umgeben von Wald eine Woche bleiben und erst danach über Jönköping, Linköping und Norrköping nach Stockholm fahren. Dort geraten wir in der Feierabendverkehr und stehen in der Hitze über knapp 2 Stunden im Stau. Der Bus hat keine Klimaanlage. Von Stockholm sehen wir eigentlich nichts. Egal, wir wollen sowieso weiter, da wir auch mal Strecke machen müssen. Und so endet der Tag auf dem <a href="http://www.eriksocamping.se/" rel="nofollow">Campingplatz Eriksö<i class="fa fa-external-link"></i></a> mitten in Stockholms Schärengarten auf Vaxholm. Am Strand befindet sich ein großer, glatter Felsen, auf dem wir gemeinsam mit anderen Touristen erneut die Abendsonne genießen.</p>
			<h2>Åland</h2>
			<p>In der 3. Woche unserer Reise machen wir uns auf nach Kapellskär, um dort die Fähre nach Mariehamn auf <a href="http://www.visitaland.com/de/" rel="nofollow">Åland<i class="fa fa-external-link"></i></a> zu nehmen. Die Überfahrt mit der M/S Rosella kostet uns nur 20 Euro und dauert erträgliche 3 1/2 Stunden. Das Wetter ist heute etwas trüber als in den vergangenen Wochen und nach gut zwei Drittel der Fahrt taucht die Insel am Horizont auf. Mit dem Fernglas kann ich die weiße Pyramide ausmachen, die nach und nach immer größer wird. Als im Hafen anlegen und das Schiff verlassen, gilt es, auf der fremden Insel einen Stellplatz zu finden. Wir fahren zunächst etwas orientierungslos herum, landen dann aber doch wieder in Mariahamn und finden den <a href="http://www.gronaudden.com/eng/index.html" rel="nofollow">Campingplatz Gröna Udden<i class="fa fa-external-link"></i></a>. Wie in Skandinavien üblich, dürfen wir uns einen Platz auf der großen Wiese selbst aussuchen. Zu unserer Freude sind nur wenige Touristen auf dem Platz und trotz der Nähe zum Ort ist es relativ ruhig hier. Wir stehen direkt hinter dem Strand und der Park erlaubt es mir, wie fast jeden Tag zu joggen. Dabei kann ich auch das Rätsel um seltsame Kreischen lösen, dass wir vom Auto aus oft gehört haben: Am Yachthafen gibt es ein kleines Gehege, auf dem etwa 10 Pfaue gehalten werden. Ich bin total begeistert und wir kommen später noch einmal mit der Kamera hierher. Ein Männchen schlägt freundlicher Weise auch sofort ein Rad. Ein schöner Anblick.</p>
			<a class="storyImage right" href="<c:out value="${imageServerUrl}${pictures['p1406044'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406044'].title}"><img alt="${pictures['p1406044'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406044'].image.imageUris['galleryStory']}" />" /></a>
			<p>Weil wir für unsere Reise noch viel Zeit haben, bleiben wir auf Åland 2 Wochen. Die folgenden Tage nutzen wir, um die Insel überwiegend mit dem Auto zu erkunden. Wir befahren die alte Poststraße, sehen das Postmuseum Postad Eckerö und die mittelalterliche Kirche Päls Böle. Der Trollstig bei Soltuna Getabergen lädt uns zu einer kleinen Wanderung ein. An dem Hang zur Küste hinab treffen wir tatsächlich auf seltsame Fabelwesen und geheimnisvolle Höhlen. Wieder zurück gibt es einen leckeren Kaffee. Die auf den Felsen angelegte Minigolfanlage lassen wir aus. Golf und eben auch Minigolf sind in Skandinavien sehr beliebt. Die Minigolfplätze sind teilweise sehr phantasievoll angelegt und machen deutlich mehr Spaß, als die Eternitplatten zuhause.</p>
			<a class="storyImage left" href="<c:out value="${imageServerUrl}${pictures['p1406057'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406057'].title}"><img alt="${pictures['p1406057'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406057'].image.imageUris['galleryStory']}" />" /></a>
			<p>Auf Åland treffen wir eher zufällig auf den Aussichtsturm Godby Fjärsundet. Für Freunde der guten Fernsicht ein Leckerbissen. Von dem aus Holz erbautem 30m hohen Turm hat man einen herrlichen Ausblick auf den Fjärsund und weite Teile der Insel. Auf einer unserer Inselerkundungen besuchen wir <a href="http://www.stallhagen.com/en/" rel="nofollow">Stallhagen Bryggeri<i class="fa fa-external-link"></i></a>. In der als Pub eingerichteten alten Kleinbrauerei werden verschiedene Biere angeboten. Was wir jedoch nicht ahnen, ist das liebevoll angerichtete sehr leckere Essen. Guten Appetit.</p>
			<h2>Finnland</h2>
			<p>Wir sind nun 4 Wochen unterwegs und nehmen die Fähre von Langnäs nach Naantali. Die gesamte Fahrt geht durch die Schären. Finnlands Schärengarten besteht aus 30.000 Inseln. Ohne den Anstieg des Meeresspiegels, wäre Åland wohl gar keine Insel, sondern Teil des finnischen Festlands. Nachdem wir das Schiff gegen Abend bei trübem Wetter verlassen haben, leitet uns die <a href="http://www.sygic.com/" rel="nofollow">Sygic-Navi-App<i class="fa fa-external-link"></i></a> das erste Mal in die Irre. Die Straßen im einsamen Hafengebiet werden zurzeit wohl aber auch umgebaut. Wir finden den Campingplatz neben dem Hafen aber trotzdem und sind angenehm überrascht. Er ist quasi am Felsen angelegt, bietet viele locker verteilte Stellplätze, eine gute Aussicht und eine ordentliche Ausstattung. Würden wir ihn nicht nur zum Übernachten nutzen wollen, könnten wir sogar von hier aus wandern.</p>
			<a class="storyImage right" href="<c:out value="${imageServerUrl}${pictures['p1406067'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406067'].title}"><img alt="${pictures['p1406067'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406067'].image.imageUris['galleryStory']}" />" /></a>
			<p>Ursprünglich wollten wir Finnland nur kurz passieren und relativ direkt nach Helsinki fahren. Weil mich die Landschaft schon immer interessiert hat und der zunächst anvisierte Campingplatz ein Flopp ist, fahren wir in die Nähe von Tampere zum <a href="http://www.taulaniemi.fi/" rel="nofollow">Campingplatz Taulaniemi<i class="fa fa-external-link"></i></a> am See Taulajärvi. Dort haben wir den wohl besten Platz unserer gesamten Reise. Der Platz ist großzügig angelegt und wir stehen mit Blick auf den See fast alleine dort. Es gibt einen Strand, Ruderboote, zwei Feuerstellen, eine Doppelsauna mit Treppe zum See sowie eine kleine Suhle mit 2 süßen Schweinen drin. Auch wenn die direkte Umgebung nicht so viel zu bieten hat, finden wir den Platz so toll, dass wir eine Woche zum chillen, paddeln und Feuer machen einlegen. Einfach nichts machen tut uns auf unserer von Sehenswürdigkeiten erfüllten Reise gut. Der Bus kann sich auch mal ausruhen.</p>
			<p>Auch im weiteren Verlauf werden wir uns in Finnland noch etwas umschauen und an dem einen oder anderen See stehen. Die Landschaft ist wirlich sehr schön und es gibt nicht so viele Mücken, wie immer befürchtet. Nun sind wir gemessen am Gesamtvorhaben zeitlich etwas im Rückstand. Wir stehen an einem Morgen früh um 6 Uhr auf, um die Fähre Helsinki/Tallinn rechtzeitig zu erreichen. Auf der Schnellstraße nach Helsinki ist für Skandinavien üblich wenig Verkehr und wir können die Landschaft Finnlands noch einmal richtig genießen. Endlose Wälder mit viele zerstreuten kleinen und großen Seen. Bestimmt werden wir ein zweites Mal nach Finnland kommen und die Gegend um Mikkeli und Varkaus erkunden. Eine halbe Stunde vor Abfahrt erreichen wir den Terminal und erfahren dann zu unserem Entsetzen, dass wir die Fähre hätten rechtzeitig buchen müssen. Es ist kein Platz mehr frei. Die nächste geht in 3 Stunden.</p>
			<h2>Estland</h2>
			<p>Wir vertreiben uns im Hafen von Helsinki irgendwie die Zeit und setzen dann gegen Mittag nach Tallinn über. Der Nachmittag genügt grad noch, um die Altstadt von <a href="http://www.visitestonia.com/en/holiday-destinations/city-guides/tallinn-the-capital" rel="nofollow">Tallinn<i class="fa fa-external-link"></i></a> zu besichtigen. Die historischen Gebäude sind in schönem Zustand. Wir sehen Kiek in den Kök, den Domberg, die Stadtmauer und natürlich die Alexander-Newski-Kathedrale. Überhaupt sehen wir unter den Menschen für uns ungewohnt viele Russen. Laut Statistik in Estland 25 Prozent der Gesamtbevölkerung. In Zeiten der Sowjetunion ist man gerne in die baltischen Staaten umgesiedelt. Wir werden später noch erfahren, dass es nicht nur in der Ukraine, sondern auch im Baltikum Konflikte zwischen Russen und Einheimischen gibt. Im Einkaufszentrum Melon bekommt man davon wenig mit. Beim Eliot-Shop kaufen wir für unglaubliche 3 Euro 500 Megabyte Surf-Guthaben. Bereits vor dem Urlaub hatte ich mir unter anderem für diesen Zweck ein neues Smartphone mit Dual-Sim-Slot gekauft. Sehr praktisch.</p>
			<a class="storyImage left" href="<c:out value="${imageServerUrl}${pictures['p1406107'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406107'].title}"><img alt="${pictures['p1406107'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406107'].image.imageUris['galleryStory']}" />" /></a>
			<p>Etwas erschöpft von den vielen Eindrücken des Tages wollen wir Tallinn nun wieder verlassen. Die Straßen sind in sehr schlechtem Zustand, die Hochhäuser außerhalb der Altstadt auch. Noch am Stadtrand sehen wir ein Atomkraftwerk, das zumindest äußerlich dem von Tschernobyl gleicht. Entgegen unserem Plan im Frühjahr fahren wir nicht direkt nach Saaremaa. Wir wollen noch den Nationalpark Lahemaa besuchen. Dieser liegt östlich von Tallinn und so fahren wir etwa 70 Kilometer auf einer schnurgeraden, einsamen Autobahn in den Abend. Es geht in den dunklen Wald, die Straßen werden noch einsamer und wir erreichen schließlich den <a href="http://www.lepispea.eu/" rel="nofollow">Campingplatz Lepispea<i class="fa fa-external-link"></i></a> bei Vösu. Es ist niemand an der Rezeption, aber wie üblich ist alles offen. Der aus Holz gezimmerte Gemeinschaftswaschraum sieht spartanisch aus. Trotzdem ist die Dusche super. Vom Bus aus vernehmen wir ein gleichmäßiges Rauschen und täuschen uns nicht: Ein paar Schritte durch den Wald und wir sind direkt am Strand. Die orangerote Abendsonne leuchtet über dem tosenden Meer durch die Wolkenschleier hindurch. Ich freue mich undendlich, hier zu sein.</p>
			<a class="storyImage right" href="<c:out value="${imageServerUrl}${pictures['p1406141'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406141'].title}"><img alt="${pictures['p1406141'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406141'].image.imageUris['galleryStory']}" />" /></a>
			<p>Wir haben den 17. Juli und schauen uns zunächst den Badeort Vösu in der Bucht von Käsmu an. Der Ort wurde wegen seiner Lage und dem guten Klima im 19. Jahrhundert zu einem bekannten Erholungs- und Badeort der Oberschicht des Russischen Reiches. Besucher kamen aus Sankt Petersburg, Moskau und sogar von der Krim, um die Sommerfrische zu genießen. Es wurden ca. 200 Sommerhäuser errichtet, die teilweise noch heute erhalten sind. Wieder zurück in die Natur geht es durch den <a href="http://www.baltikum-tours.de/infos/lahemaa.html" rel="nofollow">Nationalpark Lahemaa<i class="fa fa-external-link"></i></a>. Ein etwa 10 Kilometer langer Rundweg lässt uns nur ahnen, wie es in den sogenannten Totalreservaten aussehen mag, die von Menschen überhaupt nicht betreten werden dürfen und in denen die Natur sich selbst überlassen bleibt. Auf einem Pfad sehen wir sogar Spuren von Bärentatzen. Uns macht eher der Blick nach Oben sorgen. Ein kräftiger Regenschauer kommt immer näher. Ohne Eile, aber gerade noch rechtzeitig gelingt uns die Flucht in den Bus, in dem schon die ferngesteuerte Standheizung läuft. Ja, hier im Norden an der See ist es auch im Juli schon mal frisch draußen.</p>
			<p>Gleich neben unserem Parkplatz entdecken wir die alte Fischerkate <a href="http://www.palmse.ee/altja-korts" rel="nofollow">Altja Kõrts<i class="fa fa-external-link"></i></a> (historischer Krug). Verwöhnt von der Wärme im Bus empfinden wir ist es hier als ziemlich kühl. Das Blockhaus hat natürlich keine Heizung. Alle Gäste behalten ihre Jacken an. Die Atmosphäre des Hauses ist umso schöner und das Essen ausgezeichnet.</p>
			<a class="storyImage left" href="<c:out value="${imageServerUrl}${pictures['p1406153'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406153'].title}"><img alt="${pictures['p1406153'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406153'].image.imageUris['galleryStory']}" />" /></a>
			<p>Weil wir das Ferienhaus bereits gebucht hatten und wir schon einen Tag im Verzug sind, machen wir uns bald auf den Weg dorthin. Bei einer Rast treffen wir rein zufällig auf das <a href="http://www.laitseloss.ee/" rel="nofollow">Schloss Laitse<i class="fa fa-external-link"></i></a>. Neben dem Schloss wurde ein großer Hügel mit Knie-hohen Büschen angelegt. Die vielen Stufen des Hügels sind mit Holzleisten eingefasst. Erst auf dem zweiten Blick offenbart sich, dass es sich um ein kreisrundes Labyrinth mit zwei Eingängen handelt, dessen Ziel in der Mitte des Hügels liegt. Das wird natürlich sofort ausprobiert.</p>
			<h2>Saaremaa</h2>
			<p>Am Abend gibt es noch ein weiteres kurzes Übersetzen per Fähre. Diese Mal auf die kleine Insel Muhu, die der estnischen Ostseeinsel <a href="http://www.saaremaa.ee/" rel="nofollow">Saaremaa<i class="fa fa-external-link"></i></a> vorgelagert ist. Schließlich erreichen wir unser nächstens Etappenziel, das <a href="http://www.puhkaeestis.ee/et/rukkilille-talu" rel="nofollow">Ferienhaus Rukkilille Talu<i class="fa fa-external-link"></i></a>. Ein liebevoll restaurierter alter Stall mit Feldsteinmauern und Reetdach, umgeben von Wald, Wiesen und Wacholderhain. Die Besitzer begrüßen uns freundlich. Alles ist so, wie wir es uns gewünscht hatten. Dennoch fällt es mir sehr schwer, unsere Ausstattung aus dem VW-Bus ins Haus zu tragen.</p>
			<a class="storyImage right" href="<c:out value="${imageServerUrl}${pictures['p1406163'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406163'].title}"><img alt="${pictures['p1406163'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406163'].image.imageUris['galleryStory']}" />" /></a>
			<p>Die nächsten Wochen wollen wir nutzen, um die Insel zu erkunden. Weil das Wetter noch nicht wieder richtig aufgedreht hat, besuchen wir die Hauptstadt der Insel Kuressaare und dort die Bischofsburg Arensburg. Zunächst zaudern wir beim Eintrittspreis, kommen aber voll auf unsere Kosten. Man kann die Burg fast vollständig besichtigen. Es gibt sehr viele Räume und kleine Gänge zu erforschen. Man gelangt in den letzten Winkel bis hinauf auf die trutzigen Schutzwälle. Im Inneren der Burg befindet sich das Saaremaa-Museum, das zurzeit eine sehr vielfältige Ausstellung von Landwirtschaft und Technik des vergangenen Jahrhunderts zeigt.</p>
			<div class="clear"></div>
			<a class="storyImage left" href="<c:out value="${imageServerUrl}${pictures['p1406204'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406204'].title}"><img alt="${pictures['p1406204'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406204'].image.imageUris['galleryStory']}" />" /></a>
			<p>In den folgenenden Tagen wird es draußen auch wieder wärmer. Wir sehen den Strand Pammana, die Steilküste Panga Pank, viele Bockmühlen, Buswartehäuschen mit Gardinen und bestaunen die Kaali-Meteoritenkrater. Wir treffen die wie unsere Vermieter ebenfalls deutschen Auswanderer und Senf-Produzenten <a href="http://www.mustjala-mustard.de/" rel="nofollow">Mustjala Mustard<i class="fa fa-external-link"></i></a> in Pahapilli. Mit dem VW-Bus streifen wir durch Waldwege des Nationalparks Vilsandi um irgendwo im Nirgendwo anzukommen. Wäre das Wasser nicht so kalt, könnte man begleitet vom sanften Rauschen des Windes und dem unablässigem Gezwitscher der vielen kleinen Vögel durch das flache Wasser waten und die Insel Vilsandi erreichen. Verharrt man eine Weile und lässt den Blick über die ebene, öde und trotzdem irgendwie schöne Landschaft gleiten, glaubt man, der erste Mensch hier zu sein.</p>
			<a class="storyImage right" href="<c:out value="${imageServerUrl}${pictures['p1406217'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406217'].title}"><img alt="${pictures['p1406217'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406217'].image.imageUris['galleryStory']}" />" /></a>
			<p>In der zweiten Woche durchwandern wir das Naturschutzgebiet <a href="http://www.keskkonnaamet.ee/" rel="nofollow">Viidumäe<i class="fa fa-external-link"></i></a>. Das Gebiet liegt im ältesten Teil von Saaremaa und 85 Prozent sind bewaldet. Es gibt eine große Tier- und Pflanzenvielfallt. Selbst Orchideen findet man hier ohne lange suchen zu müssen. Wir treffen auch auf Storchschnabel, Waldhyazinthe, Knabenkraut, Händelwurz, Schachtelhalm oder den Klappertopf. Am artenreichsten sind die Gehölzwiesen, welche es europaweit nur noch in Estland gibt. Nicht so schön hört sich allerdings das Knarzen der Vorderachse am VW-Bus an. Schnell ist klar: Da geht irgendwann was kaputt.</p>
			<p>In den letzen Tagen auf Saaremaa genießen wir auch mal das Ferienhaus und die herrliche Umgebung. Hinter dem Haus sehen wir Rehe und einen Fuchs. Elche solle es geben. Beim Versuch, einen Scheit Holz vom Stapel zu nehmen, störe ich eine Ringelnatter, die sich dort gesonnt hatte. Es ist nichts passiert. Ich hatte später sogar das Glück, sie noch fotografieren zu können.</p>
			<h2>Lettland</h2>
			<a class="storyImage right" href="<c:out value="${imageServerUrl}${pictures['p1406227'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406227'].title}"><img alt="${pictures['p1406227'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406227'].image.imageUris['galleryStory']}" />" /></a>
			<p>Am Ende des zweitens Monats der Reise heißt es wieder einmal Abschied nehmen. Von einem schönen Ort. Aber auch von unseren freundlichen Vermietern. Wir müssen weiter. Es geht über Muhu, Virtsu und Pärnu nach Lettland. Der vermeintlich defekte Stoßdämpfer scheint sich wieder beruhigt zu haben. Die Straßen werden nicht besser. Selbst auf viel befahrenen Landstraßen wechseln sich neuer und reichhaltig geflickter Asphalt mit durchaus längeren Schotterpisten ab. In Baustellen gibt es nicht immer beachtete Wechselampeln. Man schlängelt sich schon mal zwischen Hütchen, Baumaschinen und ungeduldig entgegen kommenden Fahrzeugen hindurch. Wir gewöhnen uns daran und nehmen es als Gegensatz zu dem Übermaß an Regulierung im Heimatland an.</p>
			<p>Bei einer Rast an den roten Sandsteinfelsen <a href="http://www.vietas.lv/objekts/pietraga_macperu_sarkanas_klintis/" rel="nofollow">Sarkanās klintis<i class="fa fa-external-link"></i></a> kommen wir auch das erste Mal mit dem Fluss Gauja in Kontakt. Das Wetter ist eh mies und wir wollen heute noch nach Riga. Auf der Suche nach einem Campingplatz außerhalb von Riga geraten wir ungewollt in eine Art Slum. Eine Siedlung von einfachen, verkommenen Holzhütten im Wald bewohnt von offensichtlich sehr armen Menschen. Man schaut uns mit großen Augen an. Wir erreichen einen kleinen Laden, der die Rezeption eines Campingplatzes sein könnte. Auf Anfrage heißt es knapp: "Camping closed". Ich bin nicht ganz unglücklich über diese Information und wir verlassen die Gegend wieder Richtung Landstraße.</p>
			<p>Keinesfalls wollte ich in einer Stadt übernachten. Dies bleibt für heute aber die einzige Alternative. Und so entscheiden wir uns für <a href="http://www.rigacamping.lv/" rel="nofollow">"Riga City Camping"<i class="fa fa-external-link"></i></a>. Schon der Name klingt abstoßend. Es handelt sich um einen umfunktionierten Parkplatz hinter einer Fabrik im Gewerbegebiet. Zu den ansonsten gut ausgestatteten Waschräumen gelangt man durch eine Tür an einem der Gebäude. Wir vermuten, sie werden tagsüber von einer anderen Tür im Gebäude durch die Mitarbeiter betreten und genutzt. Was soll's, die Altstadt von Riga ist zu Fuß zu erreichen und demzufolge ist der Platz gut ausgebucht. Wir sehen Autokennzeichen aus fast allen Ländern Europas. So etwas habe ich in den vielen Jahren auch noch nicht erlebt.</p>
			<a class="storyImage left" href="<c:out value="${imageServerUrl}${pictures['p1406248'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406248'].title}"><img alt="${pictures['p1406248'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406248'].image.imageUris['galleryStory']}" />" /></a>
			<p>Der nächste geht es erst mal über die große Straßenbrücke in das Zentrum von <a href="http://www.latvia.travel/de/riga" rel="nofollow">Riga<i class="fa fa-external-link"></i></a>. Wir sehen die Petrikirche, den Rathausplatz mit der großen und kleinen Gilde, das Schwarzhäupterhaus und die sogenannten Drei Brüder. Eines dieser drei Häuser ist das älteste im 15. Jahrhundert aus Stein errichtete Haus Rigas. Entsprechend der Armut in ländlichen Gebieten sind wir von den prachtvollen Gebäuden in der Großstadt beeindruckt. Zum Abschluss kaufen wir auf dem Markt in Riga noch einiges an Proviant. Der Markt ist sehr weitläufig. Es gibt große Hallen, die im zweiten Weltkrieg von deutschen für Zeppeline gebaut wurden. In den Markthallen werden nun Fisch, Fleisch und andere Lebensmittelt angeboten werden. Die Vielzahl der Stände ist unüberschaubar. Wer in Riga ist, sollte unbedingt den Markt besuchen.</p>
			<p>Nachdem wir die Stadt mit vielen weiteren Sehenswürdigkeiten erkundet haben verlassen Riga wieder. Schließlich sind wir im dritten Monat und wollen noch auf der Gauja paddeln. Ein lang gehegter Wunsch. Während der Autofahrt beratschlagen wir den dafür am besten geeigneten Flussabschnitt. Ich halte mich zwar für einen geübten Paddler. Wir wollen es aber nicht gleich übers Knie beziehungsweise den Stein brechen und wählen einen wenig anspruchsvollen Abschnitt bei Sigulda. Der kleine <a href="http://www.makars.lv/de/kempings.html" rel="nofollow">Stellplatz direkt am Fluss<i class="fa fa-external-link"></i></a> macht einen gemütlichen Eindruck. Zu Fuß erreichbar ist der <a href="http://www.tarzans.lv/" rel="nofollow">"Elebnispark Tarzan"<i class="fa fa-external-link"></i></a> mit Kletterpark, Sessellift und Bobbahn. Das wollte ich doch schon immer mal!</p>
			<a class="storyImage right" href="<c:out value="${imageServerUrl}${pictures['p1406287'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406287'].title}"><img alt="${pictures['p1406287'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406287'].image.imageUris['galleryStory']}" />" /></a>
			<p>Nun kippt jedoch das Wetter. Es sind unangenehme 11 Grad bei trübem Himmel. So würde eine Flussfahrt keinen Spaß machen. Stattdessen geht es mit der ebenfalls zu Fuß erreichbaren Seilbahn über den Fluss zur Burgruine Krimulda. Der Wanderweg durch den Wald führt uns zur Gutmannshöhle und schließlich zum Museum Kulturschutzgebiet Turaida mit angeschlossener Backsteinburg. Vom Turm der Burg aus kann ich sehen, wie die <a href="http://www.baltikum-tours.de/infos/gauja.html" rel="nofollow">Gauja<i class="fa fa-external-link"></i></a> durch die Wälder mäandert. Wir wandern abends zurück zum Auto. Aus Trotz hatte ich mich sommerlich gekleidet. Nun bereue ich es leise.</p>
			<p>Auf dem Rastplatz ist es voller geworden. Auch ein paar Letten stehen nun hier. Als wir schlafen wollen, spielt nebenan das Autoradio gut hörbar und mit vielen Unterbrechungen Techno. Wir schlafen erst nachts um halb zwei. Da müssen wir wohl durch. Meine Laune wird am nächsten Tag noch mieser. Es ist immer noch kühl. Weil wir nicht mehr lange bleiben können, heißt es jetzt oder nie. Das Regenradar auf dem Smartphone wird immer dunkler. Es bleibt dabei: Zunächst kein Paddeln auf der Gauja. Es gelingt uns aber, dies später noch nachzuholen. Mit dem Platzwart besprechen wir die Transportation. Er bringt uns Aufwärts zu einer geeigneten Einsetzsetelle. Wir eleben eine wunderschöne Flussfahrt mit Felsen, Biegungen und Wendungen zurück nach Sigulda.</p>
			<h2>Litauen</h2>
			<p>Auch in Litauen werden wir viele Kilometer auf einsamen Landstraßen und Feldwegen zurücklegen. Durchstreifen Wälder und treffen auf uralte Dörfer. Schon oft haben wir Berichte im Fernsehen über diese für westlich geprägte Menschen fremde Welt gesehen. Wenn man dann eine Weile hier ist, sieht man auch viele Spuren der einstigen UDSSR. Die Natur und die überwiegend freundlichen Menschen und gefallen uns sehr. Wir fahren noch einmal vorbei an Riga, und über Umwege durch Jelgava und Siauliai nach Klaipeda. Die Route durch Litauen mündet natürlich in der weltbekannten <a href="http://www.visitneringa.com/" rel="nofollow">Kurischen Nehrung<i class="fa fa-external-link"></i></a>. Inzwischen meldet sich die Vorderachse des VW-Busses auch wieder mit lautem Knarzen bei jeder Fahrbahnunebenheit. Eine Fähre bringt uns auf den schmalen Streifen Land. Danach sind es noch 40 Kilometer Fahrt. Ich bin froh, auf dem Campingplatz <a href="http://www.kempingas.lt/" rel="nofollow">Nidos campingas<i class="fa fa-external-link"></i></a> bei Nida anzukommen. Dieser ist von gehobenem Standard. Wir sehen wieder deutlich mehr deutsche Touristen. Hauptsächlich freuen wir uns aber wieder mehr Sonne zu haben und verbringen auf der Nehrung zwischen Ostsee und Haff zwei weitere schöne Wochen.</p>
			<a class="storyImage left" href="<c:out value="${imageServerUrl}${pictures['p1406326'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406326'].title}"><img alt="${pictures['p1406326'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406326'].image.imageUris['galleryStory']}" />" /></a>
			<p>Gleich am Tag nach unserer Ankunft besteigen wir das wichtigste Ziel auf der Nehrung: Die Parniddener Düne (Hohe Düne) bei Nida und die Sonnenuhr. Von hier aus hat man einen unvergleichlichen Ausblick auf die Landzunge mit dem Wasser zu beiden Seiten. Die Sonnenuhr hat eine Besonderheit. Sie zeigt nicht nur die Stunden des Tages, sondern durch die Länge des Schattens auch Monate an. Natürlich wollen das viele Menschen sehen. Reisebusse halten hier. Wie es unsere Art ist, verlassen wir rasch die Aussichtsstelle und wandern in der Mittagssonne durch den endlosen Sand der Düne an das Haff. Unser Weg führt uns bis zum Naturschutzgebiet, das wir nicht betreten dürfen. Entlang des Zaunes in westlicher Richtung wandern wir nun auf die andere Seite der Landzunge. Unterwegs treffen wir auf Holzkreuze und Grablichter. Diese stehen hier für die unter der Düne im 19. Jahrhundert versunkenen Dörfer. Zu der Zeit kannte man noch keine Möglichkeit, die Wanderung der Düne aufzuhalten. Dörfer mussten verlassen werden und sind unter der Düne begraben.</p>
			<p>Das Land ist hier etwa 2 Kilometer breit. Es dauert nicht lange und wir hören durch den Wald die Brandung der Ostsee. Dort angekommen bietet sich uns eine völlig andere Stimmung, als am ruhigen Haff. Der Strand ist breit, der Wind weht heftig und die Wellen tosen. Mit dem Fernglas lässt sich die Grenze zu Kaliningrad ausmachen. Ich möchte dort einmal gewesen sein und wir laufen auch noch dieses Stück am Strand entlang. Nur ein einfacher Zaun aus ein paar Holzstämmen und Draht sowie Hinweisschilder trennen hier die beiden Welten. Wir beachten die Hinweise und kehren nach kurzer Rast um.</p>
			<a class="storyImage right" href="<c:out value="${imageServerUrl}${pictures['p1406337'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406337'].title}"><img alt="${pictures['p1406337'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406337'].image.imageUris['galleryStory']}" />" /></a>
			<p>Zurück auf dem Campingplatz wird ausgiebig gegrillt. Auch wenn ich mich schon daran gewöhnt hatte, mich oft englisch verständigen zu müssen: Die deutschen Touristen bieten immerhin die Möglichkeit, sich mal wieder in der eigenen Sprache unterhalten zu können. Es ist Fußball-Weltmeisterschaft. Heute spielt Deutschland gegen die USA. Ich interessiere mich sonst nicht für Fußball, höre das Spiel aber am Autoradio auf Mittelwelle. Wir gewinnen.</p>
			<p>In den folgenden Tagen auf der Kurischen Nehrung wollen wir die weitere Umgebung mit den Fahrrädern erkunden. Wir fahren über den gut ausgebauten Radweg, der überwiegend im schattigen Wald verläuft, durch die Orte Nida, Preila und Prevalka. Sehenswürdigkeiten sind hier die alten Fischerhäuser und das Thomas-Mann-Museum. Gestärkt nach einem guten Essen in der Gaststätte Kursmariu in Preila erreichen wir eines unserer Ziele, die Düne Lydumo ragas im Naglia Naturreservat. Als wir schließlich nach 45 Kilometern zurück im Hafen von Nida sind, möchte ich mit dem Teleobjektiv ein noch paar Fotos von der Düne machen. Mir kommt dann allerdings völlig überraschend ein Elch vor die Linse, der im Wasser entlang der Küste schwimmt. Dies scheint so ungewöhnlich zu sein, dass sich sogar einheimische darüber unterhalten. Den Elch sieht man dann, wenn man ihn am wenigsten erwartet.</p>
			<h2>Rückfahrt</h2>
			<p>Eigentlich war der Plan, die gesamte Strecke mit dem Auto zurückzulegen. Aber schon auf dem Weg vom Campingplatz zurück nach Klaipeda beschließen wir, von dort aus eine weitere Fähre nach Kiel zu nehmen. Der Wagen macht noch immer diese Geräusche und von einer Reparatur in Kleipeda sehen wir ab.</p>
			<p>Wir quälen uns noch einmal durch die Stadt und verbringen den Tag am Strand vor dem <a href="http://www.pajuris.info/" rel="nofollow">Pajūrio Regionalpark<i class="fa fa-external-link"></i></a>. Checkin im Hafen von Klaipeda ist ab 21:30 Uhr. Vor dem Schiff aber müssen wir weitere 3 Stunden warten und einer unglaublichen Menge an Lastwagen bei der Verladung zuschauen. Uns wird langsam klar, dass es sich in erster Linie um eine LKW-Fähre handelt und die wenigen Touristen lediglich Beifang sind. Endlich auf dem Schiff richten wir uns in der komfortablen Kabine ein. Die Kabinen um uns herum sind jedoch von lettischen und russischen LKW-Fahren bewohnt. Man kennt sich wohl und tauscht aufgeregt Neuigkeiten aus. Irgendwann nachts um 2 Uhr wird’s ruhiger.</p>
			<a class="storyImage left" href="<c:out value="${imageServerUrl}${pictures['p1406346'].image.imageUris['galleryImage']}" />" title="<spring:message code='gallery.thumnail.description'/>" data-caption="${pictures['p1406346'].title}"><img alt="${pictures['p1406346'].title}" src="<c:out value="${imageServerUrl}${pictures['p1406346'].image.imageUris['galleryStory']}" />" /></a>
			<p>Am letzten Tag unserer Reise verfolge ich an der Reling gelehnt auf dem Navi des Smartphones unsere genaue Position. Es geht entlang der polnischen und deutschen Ostseeküste. Wir sehen Bornholm, die Kalkfelsen von Rügen und die Strände von Fehmarn. Die Fahrt verläuft ruhiger, als in der Nacht. Es gibt Frühstück und zwei Mal Warm.</p>
			<p>Es ist kurz vor zehn Uhr, als wir nach einem ärgerlichen Zwischenfall mit einem hektischen und sehr ungehaltenen Einweiser das Autodeck verlassen. Wir fahren auf der A7 zurück nach Hamburg und haben es geschafft. Irgendwie ist es schade, dass auch dieser lange Urlaub schon wieder zu Ende ist. Wir sind aber glücklich, so viele kleine Abenteuer erlebt und schöne Ort gesehen zu haben. 4000 Kilometer im Auto liegen hinter uns. Wir haben 300 Liter Diesel getankt. Durch 6 Länder sind wir gefahren. 350 Fotos wurden geschossen und 2 Filme gedreht. Dem Bus geht es inzwischen wieder besser. Das rechte untere Traggelenk war defekt.</p>
			<a href="<c:url value="${displayCatalogURLs['travels']}" />" class="arrow"><spring:message code="button.backToOverview"/></a>
		</section>
		<section class="commentBox">
			<%@ include file="/jsp/pages/user/include/addCommentForm.jspf" %>
			<%@ include file="/jsp/pages/user/include/commentList.jspf" %>
		</section>
	</article>
	<div class="clear"></div>
</section>
<%@ include file="/jsp/include/footer.jspf"%>
<%@ include file="/jsp/include/htmlbody_end.jspf" %>
<script type="text/javascript">
	$(document).ready(function() {
		// Bind image box
		$('a.storyImage').colorbox({photo:true, rel:'storyImage', current: '<spring:message code="colorbox.current"/>', title: function(){return $(this).attr('data-caption');}});
		// Bind placeholder plugin
		$('input, textarea').placeholder();
		// Init. comment form handler
		var tikronComment = new TikronComment({'msg' : {author:'<spring:message code="comments.author"/>', date: '<spring:message code="comments.date"/>'}});
		tikronComment.init();
	});
</script>
<%@ include file="/jsp/include/html_end.jspf" %>
